export const LANGUAGE_BOILERPLATES = {
  "Assembly": "; Assembly (NASM 2.14.02)\nsection .data\n    msg db \"Hello, World!\", 0x0a ; string and newline character\n    len equ $ - msg             ; length of string\n\nsection .text\n    global _start\n\n_start:\n    ; write the message to stdout\n    mov edx, len   ; message length\n    mov ecx, msg   ; message address\n    mov ebx, 1     ; file descriptor 1 (stdout)\n    mov eax, 4     ; system call number (sys_write)\n    int 0x80       ; call kernel\n\n    ; exit the program\n    mov ebx, 0     ; exit code 0\n    mov eax, 1     ; system call number (sys_exit)\n    int 0x80       ; call kernel",
  "Bash": "#!/bin/bash\n# Bash (5.0.0)\n\n# Read input from stdin (if needed):\n# read input_variable\n\necho \"Hello, World!\"",
  "Basic": "' Basic (FBC 1.07.1)\n\nPRINT \"Hello, World!\"\n\n' You can read input using:\n' DIM As String input_line\n' LINE INPUT input_line",
  "C": "// C (GCC/Clang)\n#include <stdio.h>\n\nint main() {\n    // Write C code here\n    printf(\"Hello, World!\\n\");\n    return 0;\n}",
  "C++": "// C++ (GCC/Clang)\n#include <iostream>\n#include <vector>\n\nint main() {\n    // Fast I/O (optional, but good practice)\n    std::ios_base::sync_with_stdio(false);\n    std::cin.tie(NULL);\n    \n    // Write C++ code here\n    std::cout << \"Hello, World!\" << std::endl;\n    return 0;\n}",
  "Clojure": "; Clojure (1.10.1)\n(defn solve []\n  (println \"Hello, World!\")\n  ; Example of reading a line of input:\n  ; (def input (read-line))\n  )\n\n(solve)",
  "C#": "// C# (Mono 6.6.0.161)\nusing System;\n\npublic class Program\n{\n    public static void Main(string[] args)\n    {\n        // Write C# code here\n        Console.WriteLine(\"Hello, World!\");\n        \n        // Example of reading input:\n        // string line = Console.ReadLine();\n    }\n}",
  "COBOL": "IDENTIFICATION DIVISION.\nPROGRAM-ID. HELLO-WORLD.\nDATA DIVISION.\nPROCEDURE DIVISION.\nMAIN-PARA.\n    DISPLAY \"Hello, World!\".\n    STOP RUN.",
  "Common Lisp": "; Common Lisp (SBCL 2.0.0)\n\n(defun main ()\n  (format t \"Hello, World!~%\" )\n  \n  ; Example of reading input:\n  ; (let ((input (read-line)))\n  ;   (format t \"You entered: ~a~%\" input))\n  )\n\n(main)",
  "D": "// D (DMD 2.089.1)\nimport std.stdio;\n\nvoid main() {\n    // Write D code here\n    writeln(\"Hello, World!\");\n    \n    // Example of reading input:\n    // int x;\n    // readf(\"%s\\n\", &x);\n}",
  "Elixir": "# Elixir (1.9.4)\n\ndefmodule Solution do\n  def run do\n    # Write Elixir code here\n    IO.puts \"Hello, World!\"\n    \n    # Example of reading input:\n    # input = IO.gets(\"\") |> String.trim()\n  end\nend\n\nSolution.run()",
  "Erlang": "% Erlang (OTP 22.2)\n\n-module(solution).\n-export([start/0]).\n\nstart() ->\n    % Write Erlang code here\n    io:format(\"Hello, World!~n\").\n    % To read input use: io:get_line(\"\")",
  "F#": "// F# (.NET Core SDK 3.1.202)\n\n[<EntryPoint>]\nlet main argv = \n    // Write F# code here\n    printfn \"Hello, World!\"\n    \n    // Example of reading input:\n    // let input = System.Console.ReadLine()\n    0 // return an integer exit code",
  "Fortran": "! Fortran (GFortran 9.2.0)\n\nPROGRAM Solution\n  ! Write Fortran code here\n  PRINT *, 'Hello, World!'\n\n  ! Example of reading input:\n  ! READ *, input_variable\n\nEND PROGRAM Solution",
  "Go": "// Go (1.13.5)\npackage main\n\nimport \"fmt\"\n\nfunc main() {\n    // Write Go code here\n    fmt.Println(\"Hello, World!\")\n}",
  "Groovy": "// Groovy (3.0.3)\n\n// Write Groovy code here\nprintln \"Hello, World!\"\n\n// Example of reading input:\n// def line = System.in.newReader().readLine()",
  "Haskell": "-- Haskell (GHC 8.8.1)\n\nmain :: IO ()\nmain = do\n    -- Write Haskell code here\n    putStrLn \"Hello, World!\"\n    \n    -- Example of reading input:\n    -- input <- getLine\n    -- putStrLn $ \"You entered: \" ++ input",
  "Java": "// Java (OpenJDK 13.0.1)\nimport java.util.Scanner;\n\npublic class Main {\n    public static void main(String[] args) {\n        // Write Java code here\n        System.out.println(\"Hello, World!\");\n        \n        // Example of reading input:\n        // Scanner scanner = new Scanner(System.in);\n        // String line = scanner.nextLine();\n    }\n}",
  "JavaScript": "// JavaScript (Node.js 12.14.0)\n\n// Write JavaScript code here\nconsole.log(\"Hello, World!\");\n\n// To read input from stdin (typical for competitive programming):\n// const fs = require('fs');\n// const input = fs.readFileSync(0, 'utf8').trim().split('\\n');",
  "Kotlin": "// Kotlin (1.3.70)\n\nfun main() {\n    // Write Kotlin code here\n    println(\"Hello, World!\")\n    \n    // Example of reading input:\n    // val line = readLine()\n}",
  "Lua": "-- Lua (5.3.5)\n\n-- Write Lua code here\nprint(\"Hello, World!\")\n\n-- Example of reading input:\n-- local input = io.read()",
  "Objective-C": "// Objective-C (Clang 7.0.1)\n#import <Foundation/Foundation.h>\n\nint main(int argc, const char * argv[]) {\n    @autoreleasepool {\n        // Write Objective-C code here\n        NSLog(@\"Hello, World!\");\n    }\n    return 0;\n}",
  "OCaml": "(* OCaml (4.09.0) *)\n\nlet () = \n  (* Write OCaml code here *)\n  print_endline \"Hello, World!\"\n  \n  (* Example of reading input: *)\n  (* let line = read_line () in *)\n  (* Printf.printf \"You entered: %s\\n\" line *)",
  "Octave": "% Octave (5.1.0)\n\n% Write Octave code here\ndisp('Hello, World!');\n\n% Example of reading input:\n% input_variable = input('Enter value: ');",
  "Pascal": "(* Pascal (FPC 3.0.4) *)\n\nprogram Solution;\nbegin\n    (* Write Pascal code here *)\n    writeln('Hello, World!');\nend.",
  "Perl": "#!/usr/bin/perl\n# Perl (5.28.1)\n\n# Write Perl code here\nprint \"Hello, World!\\n\";\n\n# Example of reading input:\n# my $line = <STDIN>;",
  "PHP": "<?php\n// PHP (7.4.1)\n\n// Write PHP code here\necho \"Hello, World!\\n\";\n\n// Example of reading input:\n// $line = fgets(STDIN);",
  "Plain Text": "// Start writing your notes or raw text here...",
  "Prolog": "/* Prolog (GNU Prolog 1.4.5) */\n\n:- initialization(main).\n\nmain :- \n    % Write Prolog goals here\n    write('Hello, World!'), nl,\n    halt.",
  "Python": "# Python (3.8.1)\n\n# Write Python code here\nprint(\"Hello, World!\")\n\n# Example of reading input:\n# line = input()",
  "Python 2": "# Python (2.7.17)\n\n# Write Python 2 code here\nprint \"Hello, World!\"\n\n# Example of reading input:\n# line = raw_input()",
  "R": "# R (4.0.0)\n\n# Write R code here\ncat(\"Hello, World!\\n\")\n\n# Example of reading input:\n# input_var <- scan(what=\"\", nmax=1)",
  "Ruby": "# Ruby (2.7.0)\n\n# Write Ruby code here\nputs \"Hello, World!\"\n\n# Example of reading input:\n# line = gets.chomp",
  "Rust": "// Rust (1.40.0)\n\nfn main() {\n    // Write Rust code here\n    println!(\"Hello, World!\");\n    \n    // Example of reading input:\n    // let mut input = String::new();\n    // std::io::stdin().read_line(&mut input).expect(\"Failed to read line\");\n}",
  "Scala": "// Scala (2.13.2)\n\nobject Main extends App {\n    // Write Scala code here\n    println(\"Hello, World!\")\n    \n    // Example of reading input:\n    // val line = scala.io.StdIn.readLine()\n}",
  "SQL": "-- SQL (SQLite 3.27.2)\n\n-- Write your SQL query or statements here\nSELECT 'Hello, World!';\n\n-- Example of a table creation:\n-- CREATE TABLE users (id INTEGER PRIMARY KEY, name TEXT NOT NULL);",
  "Swift": "// Swift (5.2.3)\n\n// Write Swift code here\nprint(\"Hello, World!\")\n\n// Example of reading input:\n// if let line = readLine() {\n//     print(\"You entered: \\(line)\")\n// }",
  "TypeScript": "// TypeScript (3.7.4)\n\n// Write TypeScript code here\nfunction greet(name: string): void {\n    console.log(`Hello, ${name}!`);\n}\n\ngreet(\"World\");",
  "Visual Basic.Net": "' Visual Basic.Net (vbnc 0.0.0.5943)\n\nModule MainModule\n    Sub Main()\n        ' Write VB.Net code here\n        Console.WriteLine(\"Hello, World!\")\n        \n        ' Example of reading input:\n        ' Dim line As String = Console.ReadLine()\n    End Sub\nEnd Module"
}
